- name: "install erlang debian"
  block:
    - name: add repository
      shell: "wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb"
      
    - name: install erlang
      apt:
        name: 
          - esl-erlang
        state: present
        update_cache: yes
      become: True
  when: ansible_os_family == "Debian"


- name: "install erlang dependencies with yum"
  yum:
    name: erlang
    state: present
    update_cache: yes
  become: True
  when: ansible_os_family == "RedHat"
