- name: add repository
  shell: "add-apt-repository universe"
  become: True
  when: ansible_os_family == "Debian"

- name: "install python debian"
  apt:
    name: python2
    state: present
    update_cache: yes
  become: True
  when: ansible_os_family == "Debian"

- name: download get-pip.py 
  shell: "curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py"

- name: install pip 
  shell: "python get-pip.py"
  become: True

- name: install python 3
  apt: 
    name: 
      - python3
      - python3-pip
    state: present
    update_cache: yes
  become: True
  when: ansible_os_family == "Debian"

- name: "install python3 Redhat"
  yum:
    name: 
      - python3
      - python2
      - python-pip
      - python3-pip
    state: present
    update_cache: yes
  become: True
  when: ansible_os_family == "RedHat"
