format = """$status\
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$shell\
$character"""

scan_timeout = 10
add_newline = true

[line_break]
disabled = false

[character]
format = '$symbol '
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold green)'
vicmd_symbol = '[❮](bold green)'
disabled = false

[status]
format = """[(\
$symbol $int( $common_meaning) \
(\\(\uf0e7 $signal_number( $signal_name)\\)) \
\n)]($style) """
symbol = "\uf467"
not_executable_symbol = "\uf5ac"
not_found_symbol = "\uf002"
sigint_symbol = "\ufb8a"
signal_symbol = "\uf0e7"
style = 'red'
map_symbol = true
recognize_signal_code = true
disabled = false

[cmd_duration]
min_time = 2000 # Show command duration over this time
format = 'took [$duration]($style) '
style = 'yellow bold'
show_milliseconds = false
disabled = false
show_notifications = false
min_time_to_notify = 45000

[directory]
truncation_length = 5 #
truncate_to_repo = false #
fish_style_pwd_dir_length = 0
use_logical_path = true
format = "[\uf07b $path]($style)[$read_only]($read_only_style) " #
style = 'cyan' #
disabled = false
read_only = "\uf023" #
read_only_style = 'red'
truncation_symbol = '…/' #
home_symbol = '~'

[memory_usage]
threshold = 25
format = '$symbol[$ram_pct]($style) '
style = 'white dimmed'
symbol = "\ue266 "
disabled = false

[package]
format = '[$symbol$version]($style) '
symbol = "\uf487 "
style = 'yellow'
display_private = false
disabled = false

[git_branch]
format = 'on [$symbol$branch]($style)(:[$remote]($style)) '
# symbol = "\ue725 "
symbol = "\ufb2b "
# symbol = "\uf418 "
style = 'purple'
truncation_length = 9223372036854775807
truncation_symbol = '…'
only_attached = false
always_show_remote = false
disabled = false

[git_commit]
commit_hash_length = 7
format = '[\($hash$tag\)]($style) '
style = 'green'
only_detached = true
disabled = false
tag_symbol = '🏷  '
tag_disabled = true

[git_state]
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
style = 'yellow'
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = '208'
stashed = '\$'
ahead = '⇡'
behind = '⇣'
diverged = '⇕'
conflicted = '='
deleted = '✘'
renamed = '»'
modified = '!'
staged = '+'
untracked = '?'
disabled = false

[nodejs]
format = 'via [$symbol($version )]($style)'
version_format = 'v${raw}'
symbol = ' '
style = 'bold green'
disabled = false
not_capable_style = 'bold red'
detect_extensions = [
    'js',
    'mjs',
    'cjs',
    'ts',
]
detect_files = [
    'package.json',
    '.node-version',
    '.nvmrc',
]
detect_folders = ['node_modules']