- name: "install asdf global dependencies with apt"
  apt:
    name: "{{ asdf_apt_global_dependencies }}"
    install_recommends: no
  become: True
  when: ansible_os_family == "Debian"

- name: "install asdf global dependencies with yum"
  yum:
    name: "{{ asdf_yum_global_dependencies }}"
  become: True
  when: ansible_os_family == "RedHat"

- name: Clone asdf repository
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "~/.asdf"
    version: v0.8.0