- name: Install spotify dependencies
  package:
    name: "{{ spotify_dependencies }}"
    state: present
  become: True
  become_user: root
  become_method: sudo

- name: Install the spotify flatpak
  flatpak:
    name:  https://dl.flathub.org/repo/appstream/com.spotify.Client.flatpakref
    state: present
  become: True
  become_user: root
  become_method: sudo
