- name: Install spotify dependencies
  package:
    name: "{{ spotify_dependencies }}"
    state: present
  become: True
  become_user: root
  become_method: sudo

- name: Install the spotify flatpak
  community.general.flatpak:
    name:  https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref
    state: present
