- name: install snapd
  package: 
    name: snapd
    state: present
  become: yes
  become_user: root
  become_method: sudo

- name: create synlink on redhat
  shell: "ln -s /var/lib/snapd/snap /snap"
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Install snap packages
  snap:
    name: "{{ item }}"
    classic: yes
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ snaps }}"